# Generated by Django 3.2.9 on 2023-12-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='country',
            new_name='city',
        ),
    ]
