# Generated by Django 3.2.9 on 2023-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_country_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_selected_for_comparison',
            field=models.BooleanField(default=False),
        ),
    ]
