# Generated by Django 3.2.9 on 2023-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_favorite_is_selected_for_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='drive',
            field=models.CharField(blank=True, choices=[('front', 'Передний'), ('rear', 'Задний'), ('all_wheel', 'Полный')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='gears',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Автоматическая'), ('manual', 'Механическая'), ('robotized', 'Роботизированная'), ('variable', 'Вариатор')], max_length=20, null=True),
        ),
    ]
